module.exports = {
    AUTHENTICATION: "AUTHENTICATION",
    ROLE: "ROLE",
    CURRENT_BID: "CURRENT_BID",
    RECEIVER_ID: "RECEIVER_ID",
    CHAT_BOX: "CHAT_BOX",
    UPDATE_CHATBOX: "UPDATE_CHATBOX",
    MESSAGE: "MESSAGE",
    MESSAGE_REMOVE: "MESSAGE_REMOVE"
}